name: pism-cloud
channels:
  - conda-forge
dependencies:
  - python
  - geopandas
  - hyp3_sdk
  - pyarrow
  - s3fs
  - jupyter
  - toml
  - xarray
  - matplotlib
  - h5netcdf
  - h5py
  - netcdf4
  - dask[distributed]
